version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: digitalism_postgres
    environment:
      POSTGRES_DB: digitalism_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./data/docker/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d digitalism_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - digitalism_network

  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: digitalism_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@digitalism.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - digitalism_network

networks:
  digitalism_network:
    driver: bridge
